Repository ypratham/invoice-generator, pull requests merged in 2024-10, with the labels that each got.

#22 (Add) Spotify-Inspired Theme for Invoice Generator
  package-lock.json
  src/components/InvoiceWithTheme.tsx
  src/components/theme/InvoiceSpotify.tsx
Labels: enhancement, hacktoberfest-accepted

#24 Fix Date Logic in InvoiceForm Component
  src/components/InvoiceForm.tsx
Labels: bug, hacktoberfest-accepted

#27 invoice download button
  package.json
  src/components/InvoiceWithTheme.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#31 Update main with preview
  package-lock.json
  package.json
  src/components/InvoiceForm.tsx
  src/components/InvoiceWithTheme.tsx
  src/components/theme/InvoiceSpotify.tsx
Labels: hacktoberfest, hacktoberfest-accepted
